### ISSUE TITLE
demo doesn't work

### ISSUE THREAD

**Issue by jajouka79** [Bootwhmcs/bootwhmcs#67]
the theme looks interesting but the demo doesn't work

**Comment by N6REJ** [comment]
yep, demo is down

**Comment by Cam** [comment]
Yes, the demo is definitely down. Are you going to get it back up soon? I would love to see this thing in action. I'm happy to buy the "pro" version if it looks good :)

**Comment by wearelogik** [comment]
Hello,

The files got lost in "translation" sort of speak, and due to WHMCS policies, then i can't re-download the software when my support and updates "license" has expired. I have tried to get in touch with WHMCS hoping for some assistance in form of a developer license or to get the version of the files i need.

Feel free to contact me trough our website or directly if anyone can be of assistance.

**Comment by zmjwong** [comment]
Latest bootwhmcs installed here ppp.zenithmedia.ca with some test data

And you can find my modifications to the base template here https://github.com/zmjwong/bootwhmcs

Regards,

Jon Wong
jwong@zenithmedia.ca
www.zenithmedia.ca

1-514-316-1366
1-647-848-1366
1-855-ZENITH0
Extention: 1337

LinkedIn - Facebook - Twitter

**Comment by N6REJ** [comment]
Freddy I'd be happy to try to resolve this for you.  I have a dev and 
leased version and would be happy to interface with whmcs on your behalf 
if you approve of this..
http://jowwow.net/hosting is my leased site.
Bear

**Comment by wearelogik** [comment]
Hello,

The best would be if anyone who has an active WHMCS license can get a dev license that i can run as a demo on bootwhmcs.com and at the same time use to actively develop BootWHMCS to fit the frequent updates that WHMCS come with.

If you have any option to assist in such a matter, then it would be greatly appreciated.

**Comment by zmjwong** [comment]
Dev license can only be run on the same IP as the production one. Can't share it on a different domain/IP

Regards,
Jon Wong

Founder of Zenith Media Canada
Montreal - 514-316-1366
Toronto - 647-848-1366
Toll free - 1-855-ZENITH0
Extension: 1337
www.zenithmedia.ca

**Comment by challgren** [comment]
What about doing a cname

**Comment by N6REJ** [comment]
dev must be run in separate folder with restricted access or on a local 
host... I'll send a msg off to whmcs with freddy's requirements and see 
what can be done... I should hear back today.
Bear

**Comment by zmjwong** [comment]
Based on my previous discussion with the guys at whmcs the way the development licence works is:

domain name should be in the same parent as the live license. in our case our primary install is https://portal.zenithmedia.ca our dev is at http://ppp.zenithmedia.ca
And the second condition is the IP address it must match the primary paid licence. In our case 192.99.22.155.

Creating a cname for ppp.zenithmedia.ca pointing to bootwhmcs.com would just point to 104.28.10.88 / 104.28.11.88

and would not validate on whmcs side.

We spoke to them about other dev licenses etc. and the only solution they offer is above. I know its not ideal but if you look at the dev structure of cPanel they don’t even offer it, they force you to buy a full license and use that for dev.

as for the download link for 5.3.6 they don’t offer a full package for it. And 5.3.3 requires a beta tester licence.
out of luck for a legal link to 5.3.6..

Regards,

Jon Wong
jwong@zenithmedia.ca
www.zenithmedia.ca

1-514-316-1366
1-647-848-1366
1-855-ZENITH0
Extention: 1337

LinkedIn - Facebook - Twitter

**Comment by wearelogik** [comment]
As far as I know, then only the backend / admin side is affected after the install is completed. This is something I would use once in th initial setup / demo content and from there it would be front end only.
