### ISSUE TITLE
bootwhmcs.com domain has expired

### ISSUE THREAD

**Issue by rendragnet** [Bootwhmcs/bootwhmcs#70]
Hey Team,

The bootwhmcs.com domain seems to have expired :(

**Comment by Bodge-IT** [comment]
Aye, looks proper dodge.

**Comment by N6REJ** [comment]
don't be so quick freddy... Site error: the file /home/bootwhmcs.com/public/www/demo/index.php requires the ionCube PHP Loader ioncube_loader_lin_5.4.so to be installed by the website operator. If you are the website operator please use the ionCube Loader Wizard to assist with installation.

**Comment by wearelogik** [comment]
Not exactly related to the domain expiring.
