### ISSUE TITLE
...

### ISSUE THREAD

**Issue by dmasta** [Bootwhmcs/bootwhmcs#75]

**Comment by BatchHeader** [comment]
@dmasta Just wondering if this has been resolved for you?

**Comment by dmasta** [comment]
yes, fortunately it's been resolved.What a coincidence :) 
nonetheless, I appreciate it.

**Comment by BatchHeader** [comment]
@dmasta We all drop the ball at times but I am glad that @wearelogik have rectified this for you.

Can we mark this as resolved?

**Comment by dmasta** [comment]
sure, BatchHeader

**Comment by wearelogik** [comment]
Hello,

This should now be permanently solved. The automated part has malfunctioned for a while, time has limited me to look into it.

All BootPRO orders are now sent as soon as the the PayPal IPN (Instant Payment Notification) is received and verified.
