### ISSUE TITLE
bootpro for whmcs version 6.0.1

### ISSUE THREAD

**Issue by mrtieutien90** [Bootwhmcs/bootwhmcs#78]
Hello friend.
We bought pro bootpro version at: http://www.bootwhmcs.com/
However, there are some issues remain in our homepage  regarding to search domain . As we typing in domain search box and hit search button, it goes into blank all the time and we couldn't figure out what has happened
This is my site : http://billing.kogihost.com/index.php

**Comment by zmjwong** [comment]
In the admin section, go to settings, general config, security and select allow {php}, this might resolve your issue.

Regards,




Founder of Zenith Media Canada

1-514-316-1366
1-647-848-1366
1-855-ZENITH-0

@JonTheWong <https://twitter.com/JonTheWong>

www.zenithmedia.ca <https://www.zenithmedia.ca/>

**Comment by wearelogik** [comment]
Thank you @zmjwong 

@mrtieutien90 Please contact us trough the correct channels next time :) This is mostly intended for BootWHMCS related issues. http://www.bootwhmcs.com and http://www.logik.no/en/
