### ISSUE TITLE
Multiple TLD search not working

### ISSUE THREAD

**Issue by nadirlc** [Bootwhmcs/bootwhmcs#80]
Hello,

The multiple tld search option is not working on the bootwhmcs theme. For example see this url: https://secure.bipmedia.com/domainchecker.php

Thanks,
Nadir Latif

**Comment by sixtentollet** [comment]
I can confirm this bug in whmcs 6.0.2
The domeincheckers works perfectly with the standard templates.

**Comment by nadirlc** [comment]
Ok. we will contact whmcs support.

**Comment by qhjoe** [comment]
This issue now has a workaround in place in BootPRO v6.2.1

https://bootwhmcs.com/changelog
